#!/bin/bash
echo "Updating media source"
cd ../../../media
./getk
cd -
echo "Removing old media"
trash-put media
echo "Getting new media"
cp -r ../../../media media
rm -rf ./media/.git
cd ..
echo "Done"
